version: "3.3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n-yourusername.onrender.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-yourusername.onrender.com/
      - TELEGRAM_ACCESS_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
